### ISSUE TITLE
'NG_COMP_DEF' was not found in '@angular/core' - any way to support this for angular8?

### ISSUE THREAD

**Issue by thizanetti** [ngxs-labs/select-snapshot#100]
We are running angular 8 at our company and although we plan to upgrade to 9 sometime soon, that hasn't happened yet.
I was wondering how much effort do you think it is to also support angular 8?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
It doesn't support Angular 8

## Expected behavior
It could support Angular 8

## Minimal reproduction of the problem with instructions
Running npm install on node version 12.16.3 installs the package, but I get these runtime errors:

ERROR in ./node_modules/@ngxs-labs/select-snapshot/fesm2015/ngxs-labs-select-snapshot.js 136:16-28
"export 'ɵNG_COMP_DEF' was not found in '@angular/core'
ERROR in ./node_modules/@ngxs-labs/select-snapshot/fesm2015/ngxs-labs-select-snapshot.js 136:38-49
"export 'ɵNG_DIR_DEF' was not found in '@angular/core'

Looking at @angular/core, it looks like they just renamed those variables from NG_COMPONENT_DEF to NG_COMP_DEF at some point in the [past](https://github.com/angular/angular/commit/64fd0d6db947e971e47802770f79c38ec9e03d59#diff-de09a25a93c0410c75a7ff56fdc6fb572198bdbce5ecaa98cb001063018eb79e).

## What is the motivation / use case for changing the behavior?
Be able to support 1 angular major version older than it currently supports

## Environment
Libs:
- @angular/core: "~8.2.14",
- @ngxs/store": "^3.7.0"

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 86.0.622.69
 
For Tooling issues:
- Node version: 12.16.3
- Platform:  Mac

**Comment by arturovt** [comment]
It can's support Angular 8 since Angular 8 is not Ivy-ready yet. Angular 9 is the first Ivy-stable version.
