### ISSUE TITLE
select-snapshot-ivy?

### ISSUE THREAD

**Issue by xmlking** [ngxs-labs/select-snapshot#41]
learning about this project from https://medium.com/better-programming/how-i-got-rid-of-state-observables-in-angular-2c69cbbbbd0e
thanks @alessiaAmitrano
I was little confused seeing at other project https://github.com/ngxs-labs/select-snapshot-ivy

Which one show I use for Angular 9 project?
This looks like very useful for NGXS users and  reduce unnecessary  boilerplate code. when will be this integrated with NGXS?

**Comment by Jordan-Hall** [comment]
@xmlking The ivy appears to be a private package still. You should use this one

**Comment by arturovt** [comment]
I've been absent for a long time :joy: 

I gonna merge _select-snapshot-ivy_ into this package and set `@angular/core : >=9`, thus this package will be used only with those versions of Angular where Ivy is stable and enabled by default.

**Comment by arturovt** [comment]
I've published `@2.0.0`, it's compatible only with Angular 9+ since Ivy is enabled by default there. Use `@ViewSelectSnapshot` if your _selected_ property is interpolated in a template (`{{ counter }}`). It calls `markForCheck` under the hood thus it's compatible with OnPush components.
