### ISSUE TITLE
Issue when no default state is configured

### ISSUE THREAD

**Issue by aleesaan** [ngxs-labs/select-snapshot#42]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
If `SelectSnapshot` is used with a state without defaults it returns an object, which can result in issues as shown in the attached example.

## Expected behavior
I'd expect `SelectSnapshot` to return `undefined` when no default value is configured.

## Minimal reproduction of the problem with instructions
In this example you can see that the `*ngIf="animals"` check is passed even though the state isn't defined yet, which results in an error when the `*ngFor` tries to iterate over it.

https://stackblitz.com/edit/select-snapshot-initial-value

## What is the motivation / use case for changing the behavior?

In my app I have a piece of state which is undefined by default, and I initialize it after a certain server response. Since I don't need defaults for it, I don't expect `SelectSnapshot` to return an object.

**Comment by arturovt** [comment]
This is the default behaviour of all NGXS selectors. `@Select(...) animals$` will also return `{}` if you subscribe to that and this is normal. Assume that you WANT to get that empty object if the state is not defined ;)

**Comment by aleesaan** [comment]
I actually tried again with the latest version and it works, the `ngIf` check fails as it should! Thanks :)
