### ISSUE TITLE
SelectSnapshot with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by aleesaan** [ngxs-labs/select-snapshot#48]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently we can't use SelectSnapshot with `ChangeDetectionStrategy.OnPush`, or the values won't update as they should.

## Expected behavior

It would be great if we could use it with `OnPush` too. Any plans on adding support for it?

**Comment by arturovt** [comment]
I've published `@2.0.0`, it's compatible only with Angular 9+ since Ivy is enabled by default there. Use `@ViewSelectSnapshot` if your _selected_ property is interpolated in a template (`{{ counter }}`). It calls `markForCheck` under the hood thus it's compatible with OnPush components.

**Comment by arturovt** [comment]
I've forgotten to update readme... I will publish `@2.0.1` with updated readme.
